In [1]:
import pandas as pd
import numpy as np
import joblib

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_auc_score
)

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [2]:
train = pd.read_csv(r"C:\Users\ADC\Desktop\ICU_MLOps_Project\data\processed\train_processed.csv")

test = pd.read_csv(r"C:\Users\ADC\Desktop\ICU_MLOps_Project\data\processed\test_processed.csv")

print(train.shape)
print(test.shape)

(160, 8)
(40, 8)

In [3]:
X_train = train.drop("Survive", axis=1)

y_train = train["Survive"]

X_test = test.drop("Survive", axis=1)

y_test = test["Survive"]

print(X_train.shape)
print(X_test.shape)

(160, 7)
(40, 7)

In [4]:
logistic_model = LogisticRegression(random_state=42)

logistic_model.fit(X_train, y_train)

print("Logistic Regression Model Trained")

Logistic Regression Model Trained

In [5]:
logistic_predictions = logistic_model.predict(X_test)

In [6]:
accuracy = accuracy_score(y_test, logistic_predictions)

precision = precision_score(y_test, logistic_predictions)

recall = recall_score(y_test, logistic_predictions)

f1 = f1_score(y_test, logistic_predictions)

roc = roc_auc_score(y_test, logistic_predictions)

print("Accuracy :", accuracy)

print("Precision :", precision)

print("Recall :", recall)

print("F1 Score :", f1)

print("ROC AUC :", roc)

Accuracy : 0.85
Precision : 0.8611111111111112
Recall : 0.96875
F1 Score : 0.9117647058823529
ROC AUC : 0.671875

In [7]:
cm = confusion_matrix(y_test, logistic_predictions)

print(cm)

[[ 3  5]
 [ 1 31]]

In [8]:
print(classification_report(
    y_test,
    logistic_predictions
))

              precision    recall  f1-score   support

           0       0.75      0.38      0.50         8
           1       0.86      0.97      0.91        32

    accuracy                           0.85        40
   macro avg       0.81      0.67      0.71        40
weighted avg       0.84      0.85      0.83        40

In [9]:
tree = DecisionTreeClassifier(random_state=42)

tree.fit(X_train, y_train)

tree_predictions = tree.predict(X_test)

In [10]:
print("Decision Tree Accuracy")

print(accuracy_score(
    y_test,
    tree_predictions
))

Decision Tree Accuracy
0.825

In [11]:
forest = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

forest.fit(X_train, y_train)

forest_predictions = forest.predict(X_test)

In [12]:
print("Random Forest Accuracy")

print(
    accuracy_score(
        y_test,
        forest_predictions
    )
)

Random Forest Accuracy
0.825

In [13]:
gb = GradientBoostingClassifier(
    random_state=42
)

gb.fit(X_train, y_train)

gb_predictions = gb.predict(X_test)

In [14]:
print("Gradient Boosting Accuracy")

print(
    accuracy_score(
        y_test,
        gb_predictions
    )
)

Gradient Boosting Accuracy
0.775

In [15]:
results = pd.DataFrame({
    "Model":[
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "Gradient Boosting"
    ],
    "Accuracy":[
        accuracy_score(y_test, logistic_predictions),
        accuracy_score(y_test, tree_predictions),
        accuracy_score(y_test, forest_predictions),
        accuracy_score(y_test, gb_predictions)
    ]
})

results

                 Model  Accuracy
0  Logistic Regression     0.850
1        Decision Tree     0.825
2        Random Forest     0.825
3    Gradient Boosting     0.775

In [16]:
results.sort_values(
    by="Accuracy",
    ascending=False
)

                 Model  Accuracy
0  Logistic Regression     0.850
1        Decision Tree     0.825
2        Random Forest     0.825
3    Gradient Boosting     0.775

In [17]:
joblib.dump(
    forest,
    "../models/best_model.pkl"
)

print("Best Model Saved Successfully")

Best Model Saved Successfully

In [20]:
model = joblib.load(
    r"C:\Users\ADC\Desktop\ICU_MLOps_Project\models\best_model.pkl"
)

print(model)

RandomForestClassifier(random_state=42)

In [21]:
sample = X_test.iloc[[0]]

prediction = model.predict(sample)

print("Prediction :", prediction)

Prediction : [1]